package com.konfigyr.crypto;

import lombok.Value;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

import java.io.Serial;
import java.io.Serializable;
import java.time.Duration;
import java.util.Optional;

/**
 * Basic implementation of the {@link KeysetDefinition} that only contains the
 * instructions how one {@link Keyset} should be generated by the {@link KeysetFactory}.
 *
 * @author : Vladimir Spasic
 * @since : 29.08.23, Tue
 * @see KeysetFactory#create(KeyEncryptionKey, KeysetDefinition)
 **/
@Value
@NullMarked
class SimpleKeysetDefinition implements KeysetDefinition, Serializable {

	@Serial
	private static final long serialVersionUID = 283753676517870624L;

	String name;

	KeysetPurpose purpose;

	Algorithm algorithm;

	@Nullable
	Duration rotationInterval;

	@Nullable
	Duration destructionGracePeriod;

	@Override
	public Optional<@Nullable Duration> getRotationInterval() {
		return Optional.ofNullable(rotationInterval);
	}

	@Override
	public Optional<@Nullable Duration> getDestructionGracePeriod() {
		return Optional.ofNullable(destructionGracePeriod);
	}

}
