CREATE TABLE KEYSETS (
    KEYSET_NAME VARCHAR(120) NOT NULL,
    KEYSET_ALGORITHM VARCHAR(255) NOT NULL,
    KEYSET_PROVIDER VARCHAR(120) NOT NULL,
    KEYSET_KEK VARCHAR(255) NOT NULL,
    KEYSET_DATA BLOB NOT NULL,
    ROTATION_INTERVAL BIGINT,
    NEXT_ROTATION_TIME BIGINT,
    CONSTRAINT KEYSETS_PK PRIMARY KEY (KEYSET_NAME)
);
