CREATE TABLE KEYSETS (
	KEYSET_NAME VARCHAR2(120 CHAR) NOT NULL,
	KEYSET_PURPOSE VARCHAR2(50 CHAR) NOT NULL,
	KEYSET_FACTORY VARCHAR2(255 CHAR) NOT NULL,
	KEYSET_VERSION NUMBER(19,0) DEFAULT 0 NOT NULL,
	KEYSET_PROVIDER VARCHAR2(120 CHAR) NOT NULL,
	KEYSET_KEK VARCHAR2(255 CHAR) NOT NULL,
	ROTATION_INTERVAL NUMBER(19,0),
	DESTRUCTION_GRACE_PERIOD NUMBER(19,0),
	CONSTRAINT KEYSETS_PK PRIMARY KEY (KEYSET_NAME)
);

CREATE TABLE KEYSET_KEYS (
	KEYSET_NAME VARCHAR2(120 CHAR) NOT NULL,
	KEY_ID VARCHAR2(255 CHAR) NOT NULL,
	KEY_ALGORITHM VARCHAR2(255 CHAR) NOT NULL,
	KEY_TYPE VARCHAR2(50 CHAR) NOT NULL,
	KEY_STATUS VARCHAR2(50 CHAR) NOT NULL,
	KEY_PRIMARY NUMBER(1,0) NOT NULL,
	KEY_DATA BLOB,
	CREATED_AT NUMBER(19,0) NOT NULL,
	INITIALIZED_AT NUMBER(19,0),
	EXPIRES_AT NUMBER(19,0),
	DESTRUCTION_SCHEDULED_AT NUMBER(19,0),
	DESTROYED_AT NUMBER(19,0),
	CONSTRAINT KEYSET_KEYS_PK PRIMARY KEY (KEYSET_NAME, KEY_ID),
	CONSTRAINT KEYSET_KEYS_FK FOREIGN KEY (KEYSET_NAME) REFERENCES KEYSETS(KEYSET_NAME) ON DELETE CASCADE
);
