CREATE TABLE KEYSETS (
	KEYSET_NAME VARCHAR(120) NOT NULL,
	KEYSET_PURPOSE VARCHAR(50) NOT NULL,
	KEYSET_FACTORY VARCHAR(255) NOT NULL,
	KEYSET_VERSION BIGINT DEFAULT 0 NOT NULL,
	KEYSET_PROVIDER VARCHAR(120) NOT NULL,
	KEYSET_KEK VARCHAR(255) NOT NULL,
	ROTATION_INTERVAL BIGINT,
	DESTRUCTION_GRACE_PERIOD BIGINT,
	CONSTRAINT KEYSETS_PK PRIMARY KEY (KEYSET_NAME)
);

CREATE TABLE KEYSET_KEYS (
	KEYSET_NAME VARCHAR(120) NOT NULL,
	KEY_ID VARCHAR(255) NOT NULL,
	KEY_ALGORITHM VARCHAR(255) NOT NULL,
	KEY_TYPE VARCHAR(50) NOT NULL,
	KEY_STATUS VARCHAR(50) NOT NULL,
	KEY_PRIMARY BIT NOT NULL,
	KEY_DATA VARBINARY(MAX),
	CREATED_AT BIGINT NOT NULL,
	INITIALIZED_AT BIGINT,
	EXPIRES_AT BIGINT,
	DESTRUCTION_SCHEDULED_AT BIGINT,
	DESTROYED_AT BIGINT,
	CONSTRAINT KEYSET_KEYS_PK PRIMARY KEY (KEYSET_NAME, KEY_ID),
	CONSTRAINT KEYSET_KEYS_FK FOREIGN KEY (KEYSET_NAME) REFERENCES KEYSETS(KEYSET_NAME) ON DELETE CASCADE
);
