CREATE TABLE KEYSETS (
    KEYSET_NAME VARCHAR2(120 CHAR) NOT NULL,
    KEYSET_ALGORITHM VARCHAR2(255 CHAR) NOT NULL,
    KEYSET_PROVIDER VARCHAR2(120 CHAR) NOT NULL,
    KEYSET_KEK VARCHAR2(255 CHAR) NOT NULL,
    KEYSET_DATA BLOB NOT NULL,
    ROTATION_INTERVAL NUMBER(10,0),
    NEXT_ROTATION_TIME NUMBER(19,0),
    CONSTRAINT KEYSETS_PK PRIMARY KEY (KEYSET_NAME)
);
